# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"_\n\x0fRegisterRequest\x12\x1a\n\x08username\x18\x01 \x01(\tR\x08username\x12\x14\n\x05\x65mail\x18\x02 \x01(\tR\x05\x65mail\x12\x1a\n\x08password\x18\x03 \x01(\tR\x08password\"@\n\x0cLoginRequest\x12\x14\n\x05\x65mail\x18\x01 \x01(\tR\x05\x65mail\x12\x1a\n\x08password\x18\x02 \x01(\tR\x08password\"Y\n\x0c\x41uthResponse\x12\x14\n\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n\x07user_id\x18\x02 \x01(\x05R\x06userId\x12\x1a\n\x08username\x18\x03 \x01(\tR\x08username\",\n\x14ValidateTokenRequest\x12\x14\n\x05token\x18\x01 \x01(\tR\x05token\"g\n\x15ValidateTokenResponse\x12\x19\n\x08is_valid\x18\x01 \x01(\x08R\x07isValid\x12\x17\n\x07user_id\x18\x02 \x01(\x05R\x06userId\x12\x1a\n\x08username\x18\x03 \x01(\tR\x08username2\xbf\x01\n\x0b\x41uthService\x12\x35\n\x08Register\x12\x15.auth.RegisterRequest\x1a\x12.auth.AuthResponse\x12/\n\x05Login\x12\x12.auth.LoginRequest\x1a\x12.auth.AuthResponse\x12H\n\rValidateToken\x12\x1a.auth.ValidateTokenRequest\x1a\x1b.auth.ValidateTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=20
  _globals['_REGISTERREQUEST']._serialized_end=115
  _globals['_LOGINREQUEST']._serialized_start=117
  _globals['_LOGINREQUEST']._serialized_end=181
  _globals['_AUTHRESPONSE']._serialized_start=183
  _globals['_AUTHRESPONSE']._serialized_end=272
  _globals['_VALIDATETOKENREQUEST']._serialized_start=274
  _globals['_VALIDATETOKENREQUEST']._serialized_end=318
  _globals['_VALIDATETOKENRESPONSE']._serialized_start=320
  _globals['_VALIDATETOKENRESPONSE']._serialized_end=423
  _globals['_AUTHSERVICE']._serialized_start=426
  _globals['_AUTHSERVICE']._serialized_end=617
# @@protoc_insertion_point(module_scope)
