# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"_\n\x0fRegisterRequest\x12\x1a\n\x08username\x18\x01 \x01(\tR\x08username\x12\x14\n\x05\x65mail\x18\x02 \x01(\tR\x05\x65mail\x12\x1a\n\x08password\x18\x03 \x01(\tR\x08password\"@\n\x0cLoginRequest\x12\x14\n\x05\x65mail\x18\x01 \x01(\tR\x05\x65mail\x12\x1a\n\x08password\x18\x02 \x01(\tR\x08password\"Y\n\x0c\x41uthResponse\x12\x14\n\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n\x07user_id\x18\x02 \x01(\x05R\x06userId\x12\x1a\n\x08username\x18\x03 \x01(\tR\x08username\"4\n\rLogoutRequest\x12#\n\rrefresh_token\x18\x01 \x01(\tR\x0crefreshToken\"*\n\x0eLogoutResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\":\n\x13RefreshTokenRequest\x12#\n\rrefresh_token\x18\x01 \x01(\tR\x0crefreshToken\"^\n\x14RefreshTokenResponse\x12!\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\tR\x0b\x61\x63\x63\x65ssToken\x12#\n\rrefresh_token\x18\x02 \x01(\tR\x0crefreshToken\"\x18\n\x16GetPublicJWTKeyRequest\"+\n\x17GetPublicJWTKeyResponse\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key2\xc1\x02\n\x0b\x41uthService\x12\x35\n\x08Register\x12\x15.auth.RegisterRequest\x1a\x12.auth.AuthResponse\x12/\n\x05Login\x12\x12.auth.LoginRequest\x1a\x12.auth.AuthResponse\x12\x33\n\x06Logout\x12\x13.auth.LogoutRequest\x1a\x14.auth.LogoutResponse\x12\x45\n\x0cRefreshToken\x12\x19.auth.RefreshTokenRequest\x1a\x1a.auth.RefreshTokenResponse\x12N\n\x0fGetPublicJWTKey\x12\x1c.auth.GetPublicJWTKeyRequest\x1a\x1d.auth.GetPublicJWTKeyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=20
  _globals['_REGISTERREQUEST']._serialized_end=115
  _globals['_LOGINREQUEST']._serialized_start=117
  _globals['_LOGINREQUEST']._serialized_end=181
  _globals['_AUTHRESPONSE']._serialized_start=183
  _globals['_AUTHRESPONSE']._serialized_end=272
  _globals['_LOGOUTREQUEST']._serialized_start=274
  _globals['_LOGOUTREQUEST']._serialized_end=326
  _globals['_LOGOUTRESPONSE']._serialized_start=328
  _globals['_LOGOUTRESPONSE']._serialized_end=370
  _globals['_REFRESHTOKENREQUEST']._serialized_start=372
  _globals['_REFRESHTOKENREQUEST']._serialized_end=430
  _globals['_REFRESHTOKENRESPONSE']._serialized_start=432
  _globals['_REFRESHTOKENRESPONSE']._serialized_end=526
  _globals['_GETPUBLICJWTKEYREQUEST']._serialized_start=528
  _globals['_GETPUBLICJWTKEYREQUEST']._serialized_end=552
  _globals['_GETPUBLICJWTKEYRESPONSE']._serialized_start=554
  _globals['_GETPUBLICJWTKEYRESPONSE']._serialized_end=597
  _globals['_AUTHSERVICE']._serialized_start=600
  _globals['_AUTHSERVICE']._serialized_end=921
# @@protoc_insertion_point(module_scope)
