# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import message_pb2 as message__pb2


class MessageServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetChannelHistory = channel.unary_unary(
                '/message.MessageService/GetChannelHistory',
                request_serializer=message__pb2.HistoryRequest.SerializeToString,
                response_deserializer=message__pb2.HistoryResponse.FromString,
                _registered_method=True)
        self.GetDirectMessageHistory = channel.unary_unary(
                '/message.MessageService/GetDirectMessageHistory',
                request_serializer=message__pb2.DirectHistoryRequest.SerializeToString,
                response_deserializer=message__pb2.HistoryResponse.FromString,
                _registered_method=True)
        self.GetPrivateRoomId = channel.unary_unary(
                '/message.MessageService/GetPrivateRoomId',
                request_serializer=message__pb2.GetPrivateRoomIdRequest.SerializeToString,
                response_deserializer=message__pb2.GetPrivateRoomIdResponse.FromString,
                _registered_method=True)
        self.StreamLiveMessages = channel.unary_stream(
                '/message.MessageService/StreamLiveMessages',
                request_serializer=message__pb2.StreamRequest.SerializeToString,
                response_deserializer=message__pb2.MessageItem.FromString,
                _registered_method=True)
        self.CreateMessage = channel.unary_unary(
                '/message.MessageService/CreateMessage',
                request_serializer=message__pb2.CreateMessageRequest.SerializeToString,
                response_deserializer=message__pb2.MessageItem.FromString,
                _registered_method=True)
        self.CreateDirectMessage = channel.unary_unary(
                '/message.MessageService/CreateDirectMessage',
                request_serializer=message__pb2.CreateDirectMessageRequest.SerializeToString,
                response_deserializer=message__pb2.MessageItem.FromString,
                _registered_method=True)


class MessageServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetChannelHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDirectMessageHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrivateRoomId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLiveMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDirectMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetChannelHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChannelHistory,
                    request_deserializer=message__pb2.HistoryRequest.FromString,
                    response_serializer=message__pb2.HistoryResponse.SerializeToString,
            ),
            'GetDirectMessageHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDirectMessageHistory,
                    request_deserializer=message__pb2.DirectHistoryRequest.FromString,
                    response_serializer=message__pb2.HistoryResponse.SerializeToString,
            ),
            'GetPrivateRoomId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrivateRoomId,
                    request_deserializer=message__pb2.GetPrivateRoomIdRequest.FromString,
                    response_serializer=message__pb2.GetPrivateRoomIdResponse.SerializeToString,
            ),
            'StreamLiveMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLiveMessages,
                    request_deserializer=message__pb2.StreamRequest.FromString,
                    response_serializer=message__pb2.MessageItem.SerializeToString,
            ),
            'CreateMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMessage,
                    request_deserializer=message__pb2.CreateMessageRequest.FromString,
                    response_serializer=message__pb2.MessageItem.SerializeToString,
            ),
            'CreateDirectMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDirectMessage,
                    request_deserializer=message__pb2.CreateDirectMessageRequest.FromString,
                    response_serializer=message__pb2.MessageItem.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'message.MessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('message.MessageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetChannelHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.MessageService/GetChannelHistory',
            message__pb2.HistoryRequest.SerializeToString,
            message__pb2.HistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDirectMessageHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.MessageService/GetDirectMessageHistory',
            message__pb2.DirectHistoryRequest.SerializeToString,
            message__pb2.HistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrivateRoomId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.MessageService/GetPrivateRoomId',
            message__pb2.GetPrivateRoomIdRequest.SerializeToString,
            message__pb2.GetPrivateRoomIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLiveMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/message.MessageService/StreamLiveMessages',
            message__pb2.StreamRequest.SerializeToString,
            message__pb2.MessageItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.MessageService/CreateMessage',
            message__pb2.CreateMessageRequest.SerializeToString,
            message__pb2.MessageItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDirectMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.MessageService/CreateDirectMessage',
            message__pb2.CreateDirectMessageRequest.SerializeToString,
            message__pb2.MessageItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
