[package]
name = "guilds"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
envy = "0.4.2"
prost = "0.14.4"
serde = { version = "1.0.229", features = ["derive"] }
sqlx = { version = "0.9.0", features = ["chrono", "migrate", "postgres", "runtime-tokio", "uuid"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread"] }
tonic = "0.14.6"
tonic-prost = "0.14.6"
uuid = { version = "1.26.0", features = ["v4"] }
