syntax = "proto3";

package message;

service MessageService {
  rpc GetChannelHistory (HistoryRequest) returns (HistoryResponse);
  rpc StreamLiveMessages (StreamRequest) returns (stream MessageItem);
  rpc CreateMessage(CreateMessageRequest) returns (MessageItem);
}

message CreateMessageRequest {
  int32 channel_id = 1;
  string content = 2;
}

message HistoryRequest {
  int32 channel_id = 1;
  uint32 limit = 2;
  uint32 page = 3;
}

message MessageItem {
  int32 id = 1;
  int32 user_id = 2;
  int32 channel_id = 3;
  string content = 4;
  int64 timestamp = 5;
}

message HistoryResponse {
  repeated MessageItem messages = 1;
}

message StreamRequest {
  int32 channel_id = 1;
}