syntax = "proto3";

package message;

service MessageService {
  rpc GetChannelHistory (HistoryRequest) returns (HistoryResponse);
  rpc StreamLiveMessages (StreamRequest) returns (stream MessageItem);
  rpc CreateMessage(CreateMessageRequest) returns (MessageItem);
}

message CreateMessageRequest {
  string channel_id = 1;
  string user_id = 2;
  string content = 3;
}

message HistoryRequest {
  string channel_id = 1;
  uint32 limit = 2;
}

message MessageItem {
  string message_id = 1;
  string user_id = 2;
  string content = 3;
  int64 timestamp = 4;
}

message HistoryResponse {
  repeated MessageItem messages = 1;
}

message StreamRequest {
  string channel_id = 1;
}