// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateMessageRequest {
    #[prost(int32, tag="1")]
    pub channel_id: i32,
    #[prost(string, tag="2")]
    pub content: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateDirectMessageRequest {
    #[prost(int32, tag="1")]
    pub recipient_id: i32,
    #[prost(string, tag="2")]
    pub content: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HistoryRequest {
    #[prost(int32, tag="1")]
    pub channel_id: i32,
    #[prost(uint32, tag="2")]
    pub limit: u32,
    #[prost(uint32, tag="3")]
    pub page: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DirectHistoryRequest {
    #[prost(int32, tag="1")]
    pub recipient_id: i32,
    #[prost(uint32, tag="2")]
    pub limit: u32,
    #[prost(uint32, tag="3")]
    pub page: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageItem {
    #[prost(int32, tag="1")]
    pub id: i32,
    #[prost(int32, tag="2")]
    pub user_id: i32,
    #[prost(int32, tag="3")]
    pub channel_id: i32,
    #[prost(string, tag="4")]
    pub content: ::prost::alloc::string::String,
    #[prost(int64, tag="5")]
    pub timestamp: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HistoryResponse {
    #[prost(message, repeated, tag="1")]
    pub messages: ::prost::alloc::vec::Vec<MessageItem>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPrivateRoomIdRequest {
    #[prost(int32, tag="1")]
    pub recipient_id: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPrivateRoomIdResponse {
    #[prost(int32, tag="1")]
    pub channel_id: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamRequest {
    #[prost(int32, tag="1")]
    pub channel_id: i32,
}
include!("message.tonic.rs");
// @@protoc_insertion_point(module)