// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: message.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "message";

export interface CreateMessageRequest {
  channelId: number;
  content: string;
}

export interface HistoryRequest {
  channelId: number;
  limit: number;
}

export interface MessageItem {
  id: number;
  userId: number;
  channelId: number;
  content: string;
  timestamp: number;
}

export interface HistoryResponse {
  messages: MessageItem[];
}

export interface StreamRequest {
  channelId: number;
}

function createBaseCreateMessageRequest(): CreateMessageRequest {
  return { channelId: 0, content: "" };
}

export const CreateMessageRequest: MessageFns<CreateMessageRequest> = {
  encode(message: CreateMessageRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.channelId !== 0) {
      writer.uint32(8).int32(message.channelId);
    }
    if (message.content !== "") {
      writer.uint32(18).string(message.content);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateMessageRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateMessageRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.channelId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.content = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateMessageRequest {
    return {
      channelId: isSet(object.channelId)
        ? globalThis.Number(object.channelId)
        : isSet(object.channel_id)
        ? globalThis.Number(object.channel_id)
        : 0,
      content: isSet(object.content) ? globalThis.String(object.content) : "",
    };
  },

  toJSON(message: CreateMessageRequest): unknown {
    const obj: any = {};
    if (message.channelId !== 0) {
      obj.channelId = Math.round(message.channelId);
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateMessageRequest>, I>>(base?: I): CreateMessageRequest {
    return CreateMessageRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateMessageRequest>, I>>(object: I): CreateMessageRequest {
    const message = createBaseCreateMessageRequest();
    message.channelId = object.channelId ?? 0;
    message.content = object.content ?? "";
    return message;
  },
};

function createBaseHistoryRequest(): HistoryRequest {
  return { channelId: 0, limit: 0 };
}

export const HistoryRequest: MessageFns<HistoryRequest> = {
  encode(message: HistoryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.channelId !== 0) {
      writer.uint32(8).int32(message.channelId);
    }
    if (message.limit !== 0) {
      writer.uint32(16).uint32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HistoryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHistoryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.channelId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HistoryRequest {
    return {
      channelId: isSet(object.channelId)
        ? globalThis.Number(object.channelId)
        : isSet(object.channel_id)
        ? globalThis.Number(object.channel_id)
        : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
    };
  },

  toJSON(message: HistoryRequest): unknown {
    const obj: any = {};
    if (message.channelId !== 0) {
      obj.channelId = Math.round(message.channelId);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HistoryRequest>, I>>(base?: I): HistoryRequest {
    return HistoryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HistoryRequest>, I>>(object: I): HistoryRequest {
    const message = createBaseHistoryRequest();
    message.channelId = object.channelId ?? 0;
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseMessageItem(): MessageItem {
  return { id: 0, userId: 0, channelId: 0, content: "", timestamp: 0 };
}

export const MessageItem: MessageFns<MessageItem> = {
  encode(message: MessageItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.userId !== 0) {
      writer.uint32(16).int32(message.userId);
    }
    if (message.channelId !== 0) {
      writer.uint32(24).int32(message.channelId);
    }
    if (message.content !== "") {
      writer.uint32(34).string(message.content);
    }
    if (message.timestamp !== 0) {
      writer.uint32(40).int64(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MessageItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessageItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.userId = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.channelId = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MessageItem {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      userId: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      channelId: isSet(object.channelId)
        ? globalThis.Number(object.channelId)
        : isSet(object.channel_id)
        ? globalThis.Number(object.channel_id)
        : 0,
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
    };
  },

  toJSON(message: MessageItem): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.channelId !== 0) {
      obj.channelId = Math.round(message.channelId);
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MessageItem>, I>>(base?: I): MessageItem {
    return MessageItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MessageItem>, I>>(object: I): MessageItem {
    const message = createBaseMessageItem();
    message.id = object.id ?? 0;
    message.userId = object.userId ?? 0;
    message.channelId = object.channelId ?? 0;
    message.content = object.content ?? "";
    message.timestamp = object.timestamp ?? 0;
    return message;
  },
};

function createBaseHistoryResponse(): HistoryResponse {
  return { messages: [] };
}

export const HistoryResponse: MessageFns<HistoryResponse> = {
  encode(message: HistoryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.messages) {
      MessageItem.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HistoryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHistoryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.messages.push(MessageItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HistoryResponse {
    return {
      messages: globalThis.Array.isArray(object?.messages)
        ? object.messages.map((e: any) => MessageItem.fromJSON(e))
        : [],
    };
  },

  toJSON(message: HistoryResponse): unknown {
    const obj: any = {};
    if (message.messages?.length) {
      obj.messages = message.messages.map((e) => MessageItem.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HistoryResponse>, I>>(base?: I): HistoryResponse {
    return HistoryResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HistoryResponse>, I>>(object: I): HistoryResponse {
    const message = createBaseHistoryResponse();
    message.messages = object.messages?.map((e) => MessageItem.fromPartial(e)) || [];
    return message;
  },
};

function createBaseStreamRequest(): StreamRequest {
  return { channelId: 0 };
}

export const StreamRequest: MessageFns<StreamRequest> = {
  encode(message: StreamRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.channelId !== 0) {
      writer.uint32(8).int32(message.channelId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StreamRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStreamRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.channelId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StreamRequest {
    return {
      channelId: isSet(object.channelId)
        ? globalThis.Number(object.channelId)
        : isSet(object.channel_id)
        ? globalThis.Number(object.channel_id)
        : 0,
    };
  },

  toJSON(message: StreamRequest): unknown {
    const obj: any = {};
    if (message.channelId !== 0) {
      obj.channelId = Math.round(message.channelId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StreamRequest>, I>>(base?: I): StreamRequest {
    return StreamRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StreamRequest>, I>>(object: I): StreamRequest {
    const message = createBaseStreamRequest();
    message.channelId = object.channelId ?? 0;
    return message;
  },
};

export type MessageServiceService = typeof MessageServiceService;
export const MessageServiceService = {
  getChannelHistory: {
    path: "/message.MessageService/GetChannelHistory" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HistoryRequest): Buffer => Buffer.from(HistoryRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HistoryRequest => HistoryRequest.decode(value),
    responseSerialize: (value: HistoryResponse): Buffer => Buffer.from(HistoryResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HistoryResponse => HistoryResponse.decode(value),
  },
  streamLiveMessages: {
    path: "/message.MessageService/StreamLiveMessages" as const,
    requestStream: false as const,
    responseStream: true as const,
    requestSerialize: (value: StreamRequest): Buffer => Buffer.from(StreamRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): StreamRequest => StreamRequest.decode(value),
    responseSerialize: (value: MessageItem): Buffer => Buffer.from(MessageItem.encode(value).finish()),
    responseDeserialize: (value: Buffer): MessageItem => MessageItem.decode(value),
  },
  createMessage: {
    path: "/message.MessageService/CreateMessage" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateMessageRequest): Buffer => Buffer.from(CreateMessageRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateMessageRequest => CreateMessageRequest.decode(value),
    responseSerialize: (value: MessageItem): Buffer => Buffer.from(MessageItem.encode(value).finish()),
    responseDeserialize: (value: Buffer): MessageItem => MessageItem.decode(value),
  },
} as const;

export interface MessageServiceServer extends UntypedServiceImplementation {
  getChannelHistory: handleUnaryCall<HistoryRequest, HistoryResponse>;
  streamLiveMessages: handleServerStreamingCall<StreamRequest, MessageItem>;
  createMessage: handleUnaryCall<CreateMessageRequest, MessageItem>;
}

export interface MessageServiceClient extends Client {
  getChannelHistory(
    request: HistoryRequest,
    callback: (error: ServiceError | null, response: HistoryResponse) => void,
  ): ClientUnaryCall;
  getChannelHistory(
    request: HistoryRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: HistoryResponse) => void,
  ): ClientUnaryCall;
  getChannelHistory(
    request: HistoryRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: HistoryResponse) => void,
  ): ClientUnaryCall;
  streamLiveMessages(request: StreamRequest, options?: Partial<CallOptions>): ClientReadableStream<MessageItem>;
  streamLiveMessages(
    request: StreamRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<MessageItem>;
  createMessage(
    request: CreateMessageRequest,
    callback: (error: ServiceError | null, response: MessageItem) => void,
  ): ClientUnaryCall;
  createMessage(
    request: CreateMessageRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: MessageItem) => void,
  ): ClientUnaryCall;
  createMessage(
    request: CreateMessageRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: MessageItem) => void,
  ): ClientUnaryCall;
}

export const MessageServiceClient = makeGenericClientConstructor(
  MessageServiceService,
  "message.MessageService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): MessageServiceClient;
  service: typeof MessageServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
